// Map Location Mappings
locPercept(location(0,0),left(none),right(none),up(none),down(none)).
locPercept(location(0,1),left(none),right(none),up(none),down(none)).
locPercept(location(0,2),left(none),right(obstacle),up(none),down(none)).
locPercept(location(0,3),left(none),right(none),up(none),down(none)).
locPercept(location(0,4),left(none),right(none),up(none),down(none)).
locPercept(location(0,5),left(none),right(none),up(none),down(none)).
locPercept(location(0,6),left(none),right(none),up(none),down(none)).
locPercept(location(0,7),left(none),right(none),up(none),down(none)).
locPercept(location(0,8),left(none),right(none),up(none),down(none)).
locPercept(location(0,9),left(none),right(none),up(none),down(none)).
locPercept(location(1,0),left(none),right(none),up(none),down(none)).
locPercept(location(1,1),left(none),right(none),up(none),down(obstacle)).
locPercept(location(1,3),left(none),right(none),up(obstacle),down(none)).
locPercept(location(1,4),left(none),right(none),up(none),down(none)).
locPercept(location(1,5),left(none),right(none),up(none),down(none)).
locPercept(location(1,6),left(none),right(none),up(none),down(none)).
locPercept(location(1,7),left(none),right(none),up(none),down(none)).
locPercept(location(1,8),left(none),right(none),up(none),down(none)).
locPercept(location(1,9),left(none),right(none),up(none),down(none)).
locPercept(location(2,0),left(none),right(none),up(none),down(none)).
locPercept(location(2,1),left(none),right(none),up(none),down(obstacle)).
locPercept(location(2,3),left(none),right(none),up(obstacle),down(none)).
locPercept(location(2,4),left(none),right(none),up(none),down(none)).
locPercept(location(2,5),left(none),right(none),up(none),down(none)).
locPercept(location(2,6),left(none),right(none),up(none),down(none)).
locPercept(location(2,7),left(none),right(none),up(none),down(none)).
locPercept(location(2,8),left(none),right(none),up(none),down(none)).
locPercept(location(2,9),left(none),right(none),up(none),down(none)).
locPercept(location(3,0),left(none),right(none),up(none),down(none)).
locPercept(location(3,1),left(none),right(none),up(none),down(none)).
locPercept(location(3,2),left(obstacle),right(none),up(none),down(none)).
locPercept(location(3,3),left(none),right(none),up(none),down(none)).
locPercept(location(3,4),left(none),right(none),up(none),down(none)).
locPercept(location(3,5),left(none),right(none),up(none),down(none)).
locPercept(location(3,6),left(none),right(none),up(none),down(none)).
locPercept(location(3,7),left(none),right(none),up(none),down(none)).
locPercept(location(3,8),left(none),right(none),up(none),down(none)).
locPercept(location(3,9),left(none),right(none),up(none),down(none)).
locPercept(location(4,0),left(none),right(none),up(none),down(none)).
locPercept(location(4,1),left(none),right(none),up(none),down(none)).
locPercept(location(4,2),left(none),right(none),up(none),down(none)).
locPercept(location(4,3),left(none),right(none),up(none),down(none)).
locPercept(location(4,4),left(none),right(none),up(none),down(none)).
locPercept(location(4,5),left(none),right(none),up(none),down(none)).
locPercept(location(4,6),left(none),right(none),up(none),down(none)).
locPercept(location(4,7),left(none),right(none),up(none),down(none)).
locPercept(location(4,8),left(none),right(none),up(none),down(none)).
locPercept(location(4,9),left(none),right(none),up(none),down(none)).
locPercept(location(5,0),left(none),right(none),up(none),down(none)).
locPercept(location(5,1),left(none),right(none),up(none),down(none)).
locPercept(location(5,2),left(none),right(none),up(none),down(none)).
locPercept(location(5,3),left(none),right(none),up(none),down(none)).
locPercept(location(5,4),left(none),right(none),up(none),down(none)).
locPercept(location(5,5),left(none),right(none),up(none),down(none)).
locPercept(location(5,6),left(none),right(none),up(none),down(none)).
locPercept(location(5,7),left(none),right(none),up(none),down(none)).
locPercept(location(5,8),left(none),right(none),up(none),down(none)).
locPercept(location(5,9),left(none),right(none),up(none),down(none)).
locPercept(location(6,0),left(none),right(none),up(none),down(none)).
locPercept(location(6,1),left(none),right(none),up(none),down(none)).
locPercept(location(6,2),left(none),right(none),up(none),down(none)).
locPercept(location(6,3),left(none),right(none),up(none),down(none)).
locPercept(location(6,4),left(none),right(none),up(none),down(none)).
locPercept(location(6,5),left(none),right(none),up(none),down(none)).
locPercept(location(6,6),left(none),right(none),up(none),down(none)).
locPercept(location(6,7),left(none),right(none),up(none),down(none)).
locPercept(location(6,8),left(none),right(none),up(none),down(none)).
locPercept(location(6,9),left(none),right(none),up(none),down(none)).
locPercept(location(7,0),left(none),right(none),up(none),down(none)).
locPercept(location(7,1),left(none),right(none),up(none),down(none)).
locPercept(location(7,2),left(none),right(none),up(none),down(none)).
locPercept(location(7,3),left(none),right(none),up(none),down(none)).
locPercept(location(7,4),left(none),right(none),up(none),down(none)).
locPercept(location(7,5),left(none),right(none),up(none),down(none)).
locPercept(location(7,6),left(none),right(none),up(none),down(none)).
locPercept(location(7,7),left(none),right(none),up(none),down(none)).
locPercept(location(7,8),left(none),right(none),up(none),down(none)).
locPercept(location(7,9),left(none),right(none),up(none),down(none)).
locPercept(location(8,0),left(none),right(none),up(none),down(none)).
locPercept(location(8,1),left(none),right(none),up(none),down(none)).
locPercept(location(8,2),left(none),right(none),up(none),down(none)).
locPercept(location(8,3),left(none),right(none),up(none),down(none)).
locPercept(location(8,4),left(none),right(none),up(none),down(none)).
locPercept(location(8,5),left(none),right(none),up(none),down(none)).
locPercept(location(8,6),left(none),right(none),up(none),down(none)).
locPercept(location(8,7),left(none),right(none),up(none),down(none)).
locPercept(location(8,8),left(none),right(none),up(none),down(none)).
locPercept(location(8,9),left(none),right(none),up(none),down(none)).
locPercept(location(9,0),left(none),right(none),up(none),down(none)).
locPercept(location(9,1),left(none),right(none),up(none),down(none)).
locPercept(location(9,2),left(none),right(none),up(none),down(none)).
locPercept(location(9,3),left(none),right(none),up(none),down(none)).
locPercept(location(9,4),left(none),right(none),up(none),down(none)).
locPercept(location(9,5),left(none),right(none),up(none),down(none)).
locPercept(location(9,6),left(none),right(none),up(none),down(none)).
locPercept(location(9,7),left(none),right(none),up(none),down(none)).
locPercept(location(9,8),left(none),right(none),up(none),down(none)).
locPercept(location(9,9),left(none),right(none),up(none),down(none)).

// Adjacent Location Mappings
locAdjacent(location(0,0),[adjacent(down,location(0,1)),adjacent(right,location(1,0))]).
locAdjacent(location(0,1),[adjacent(up,location(0,0)),adjacent(down,location(0,2)),adjacent(right,location(1,1))]).
locAdjacent(location(0,2),[adjacent(up,location(0,1)),adjacent(down,location(0,3))]).
locAdjacent(location(0,3),[adjacent(up,location(0,2)),adjacent(down,location(0,4)),adjacent(right,location(1,3))]).
locAdjacent(location(0,4),[adjacent(up,location(0,3)),adjacent(down,location(0,5)),adjacent(right,location(1,4))]).
locAdjacent(location(0,5),[adjacent(up,location(0,4)),adjacent(down,location(0,6)),adjacent(right,location(1,5))]).
locAdjacent(location(0,6),[adjacent(up,location(0,5)),adjacent(down,location(0,7)),adjacent(right,location(1,6))]).
locAdjacent(location(0,7),[adjacent(up,location(0,6)),adjacent(down,location(0,8)),adjacent(right,location(1,7))]).
locAdjacent(location(0,8),[adjacent(up,location(0,7)),adjacent(down,location(0,9)),adjacent(right,location(1,8))]).
locAdjacent(location(0,9),[adjacent(up,location(0,8)),adjacent(right,location(1,9))]).
locAdjacent(location(1,0),[adjacent(right,location(2,0)),adjacent(down,location(1,1)),adjacent(left,location(0,0))]).
locAdjacent(location(1,1),[adjacent(right,location(2,1)),adjacent(up,location(1,0)),adjacent(left,location(0,1))]).
locAdjacent(location(1,3),[adjacent(right,location(2,3)),adjacent(down,location(1,4)),adjacent(left,location(0,3))]).
locAdjacent(location(1,4),[adjacent(right,location(2,4)),adjacent(up,location(1,3)),adjacent(down,location(1,5)),adjacent(left,location(0,4))]).
locAdjacent(location(1,5),[adjacent(right,location(2,5)),adjacent(up,location(1,4)),adjacent(down,location(1,6)),adjacent(left,location(0,5))]).
locAdjacent(location(1,6),[adjacent(right,location(2,6)),adjacent(up,location(1,5)),adjacent(down,location(1,7)),adjacent(left,location(0,6))]).
locAdjacent(location(1,7),[adjacent(right,location(2,7)),adjacent(up,location(1,6)),adjacent(down,location(1,8)),adjacent(left,location(0,7))]).
locAdjacent(location(1,8),[adjacent(right,location(2,8)),adjacent(up,location(1,7)),adjacent(down,location(1,9)),adjacent(left,location(0,8))]).
locAdjacent(location(1,9),[adjacent(right,location(2,9)),adjacent(up,location(1,8)),adjacent(left,location(0,9))]).
locAdjacent(location(2,0),[adjacent(down,location(2,1)),adjacent(left,location(1,0)),adjacent(right,location(3,0))]).
locAdjacent(location(2,1),[adjacent(up,location(2,0)),adjacent(left,location(1,1)),adjacent(right,location(3,1))]).
locAdjacent(location(2,3),[adjacent(down,location(2,4)),adjacent(left,location(1,3)),adjacent(right,location(3,3))]).
locAdjacent(location(2,4),[adjacent(up,location(2,3)),adjacent(down,location(2,5)),adjacent(left,location(1,4)),adjacent(right,location(3,4))]).
locAdjacent(location(2,5),[adjacent(up,location(2,4)),adjacent(down,location(2,6)),adjacent(left,location(1,5)),adjacent(right,location(3,5))]).
locAdjacent(location(2,6),[adjacent(up,location(2,5)),adjacent(down,location(2,7)),adjacent(left,location(1,6)),adjacent(right,location(3,6))]).
locAdjacent(location(2,7),[adjacent(up,location(2,6)),adjacent(down,location(2,8)),adjacent(left,location(1,7)),adjacent(right,location(3,7))]).
locAdjacent(location(2,8),[adjacent(up,location(2,7)),adjacent(down,location(2,9)),adjacent(left,location(1,8)),adjacent(right,location(3,8))]).
locAdjacent(location(2,9),[adjacent(up,location(2,8)),adjacent(left,location(1,9)),adjacent(right,location(3,9))]).
locAdjacent(location(3,0),[adjacent(right,location(4,0)),adjacent(down,location(3,1)),adjacent(left,location(2,0))]).
locAdjacent(location(3,1),[adjacent(right,location(4,1)),adjacent(down,location(3,2)),adjacent(up,location(3,0)),adjacent(left,location(2,1))]).
locAdjacent(location(3,2),[adjacent(right,location(4,2)),adjacent(down,location(3,3)),adjacent(up,location(3,1))]).
locAdjacent(location(3,3),[adjacent(right,location(4,3)),adjacent(up,location(3,2)),adjacent(down,location(3,4)),adjacent(left,location(2,3))]).
locAdjacent(location(3,4),[adjacent(right,location(4,4)),adjacent(up,location(3,3)),adjacent(down,location(3,5)),adjacent(left,location(2,4))]).
locAdjacent(location(3,5),[adjacent(right,location(4,5)),adjacent(up,location(3,4)),adjacent(down,location(3,6)),adjacent(left,location(2,5))]).
locAdjacent(location(3,6),[adjacent(right,location(4,6)),adjacent(up,location(3,5)),adjacent(down,location(3,7)),adjacent(left,location(2,6))]).
locAdjacent(location(3,7),[adjacent(right,location(4,7)),adjacent(up,location(3,6)),adjacent(down,location(3,8)),adjacent(left,location(2,7))]).
locAdjacent(location(3,8),[adjacent(right,location(4,8)),adjacent(up,location(3,7)),adjacent(down,location(3,9)),adjacent(left,location(2,8))]).
locAdjacent(location(3,9),[adjacent(right,location(4,9)),adjacent(up,location(3,8)),adjacent(left,location(2,9))]).
locAdjacent(location(4,0),[adjacent(down,location(4,1)),adjacent(left,location(3,0)),adjacent(right,location(5,0))]).
locAdjacent(location(4,1),[adjacent(up,location(4,0)),adjacent(down,location(4,2)),adjacent(left,location(3,1)),adjacent(right,location(5,1))]).
locAdjacent(location(4,2),[adjacent(down,location(4,3)),adjacent(up,location(4,1)),adjacent(left,location(3,2)),adjacent(right,location(5,2))]).
locAdjacent(location(4,3),[adjacent(down,location(4,4)),adjacent(up,location(4,2)),adjacent(left,location(3,3)),adjacent(right,location(5,3))]).
locAdjacent(location(4,4),[adjacent(up,location(4,3)),adjacent(down,location(4,5)),adjacent(left,location(3,4)),adjacent(right,location(5,4))]).
locAdjacent(location(4,5),[adjacent(up,location(4,4)),adjacent(down,location(4,6)),adjacent(left,location(3,5)),adjacent(right,location(5,5))]).
locAdjacent(location(4,6),[adjacent(up,location(4,5)),adjacent(down,location(4,7)),adjacent(left,location(3,6)),adjacent(right,location(5,6))]).
locAdjacent(location(4,7),[adjacent(up,location(4,6)),adjacent(down,location(4,8)),adjacent(left,location(3,7)),adjacent(right,location(5,7))]).
locAdjacent(location(4,8),[adjacent(up,location(4,7)),adjacent(down,location(4,9)),adjacent(left,location(3,8)),adjacent(right,location(5,8))]).
locAdjacent(location(4,9),[adjacent(up,location(4,8)),adjacent(left,location(3,9)),adjacent(right,location(5,9))]).
locAdjacent(location(5,0),[adjacent(right,location(6,0)),adjacent(down,location(5,1)),adjacent(left,location(4,0))]).
locAdjacent(location(5,1),[adjacent(right,location(6,1)),adjacent(up,location(5,0)),adjacent(down,location(5,2)),adjacent(left,location(4,1))]).
locAdjacent(location(5,2),[adjacent(right,location(6,2)),adjacent(up,location(5,1)),adjacent(down,location(5,3)),adjacent(left,location(4,2))]).
locAdjacent(location(5,3),[adjacent(right,location(6,3)),adjacent(down,location(5,4)),adjacent(up,location(5,2)),adjacent(left,location(4,3))]).
locAdjacent(location(5,4),[adjacent(right,location(6,4)),adjacent(up,location(5,3)),adjacent(down,location(5,5)),adjacent(left,location(4,4))]).
locAdjacent(location(5,5),[adjacent(right,location(6,5)),adjacent(up,location(5,4)),adjacent(down,location(5,6)),adjacent(left,location(4,5))]).
locAdjacent(location(5,6),[adjacent(right,location(6,6)),adjacent(up,location(5,5)),adjacent(down,location(5,7)),adjacent(left,location(4,6))]).
locAdjacent(location(5,7),[adjacent(right,location(6,7)),adjacent(up,location(5,6)),adjacent(down,location(5,8)),adjacent(left,location(4,7))]).
locAdjacent(location(5,8),[adjacent(right,location(6,8)),adjacent(up,location(5,7)),adjacent(down,location(5,9)),adjacent(left,location(4,8))]).
locAdjacent(location(5,9),[adjacent(right,location(6,9)),adjacent(up,location(5,8)),adjacent(left,location(4,9))]).
locAdjacent(location(6,0),[adjacent(down,location(6,1)),adjacent(left,location(5,0)),adjacent(right,location(7,0))]).
locAdjacent(location(6,1),[adjacent(up,location(6,0)),adjacent(down,location(6,2)),adjacent(left,location(5,1)),adjacent(right,location(7,1))]).
locAdjacent(location(6,2),[adjacent(up,location(6,1)),adjacent(down,location(6,3)),adjacent(left,location(5,2)),adjacent(right,location(7,2))]).
locAdjacent(location(6,3),[adjacent(up,location(6,2)),adjacent(down,location(6,4)),adjacent(left,location(5,3)),adjacent(right,location(7,3))]).
locAdjacent(location(6,4),[adjacent(up,location(6,3)),adjacent(down,location(6,5)),adjacent(left,location(5,4)),adjacent(right,location(7,4))]).
locAdjacent(location(6,5),[adjacent(up,location(6,4)),adjacent(down,location(6,6)),adjacent(left,location(5,5)),adjacent(right,location(7,5))]).
locAdjacent(location(6,6),[adjacent(up,location(6,5)),adjacent(down,location(6,7)),adjacent(left,location(5,6)),adjacent(right,location(7,6))]).
locAdjacent(location(6,7),[adjacent(up,location(6,6)),adjacent(down,location(6,8)),adjacent(left,location(5,7)),adjacent(right,location(7,7))]).
locAdjacent(location(6,8),[adjacent(up,location(6,7)),adjacent(down,location(6,9)),adjacent(left,location(5,8)),adjacent(right,location(7,8))]).
locAdjacent(location(6,9),[adjacent(up,location(6,8)),adjacent(left,location(5,9)),adjacent(right,location(7,9))]).
locAdjacent(location(7,0),[adjacent(right,location(8,0)),adjacent(down,location(7,1)),adjacent(left,location(6,0))]).
locAdjacent(location(7,1),[adjacent(right,location(8,1)),adjacent(up,location(7,0)),adjacent(down,location(7,2)),adjacent(left,location(6,1))]).
locAdjacent(location(7,2),[adjacent(right,location(8,2)),adjacent(up,location(7,1)),adjacent(down,location(7,3)),adjacent(left,location(6,2))]).
locAdjacent(location(7,3),[adjacent(right,location(8,3)),adjacent(up,location(7,2)),adjacent(down,location(7,4)),adjacent(left,location(6,3))]).
locAdjacent(location(7,4),[adjacent(right,location(8,4)),adjacent(up,location(7,3)),adjacent(down,location(7,5)),adjacent(left,location(6,4))]).
locAdjacent(location(7,5),[adjacent(right,location(8,5)),adjacent(up,location(7,4)),adjacent(down,location(7,6)),adjacent(left,location(6,5))]).
locAdjacent(location(7,6),[adjacent(right,location(8,6)),adjacent(up,location(7,5)),adjacent(down,location(7,7)),adjacent(left,location(6,6))]).
locAdjacent(location(7,7),[adjacent(right,location(8,7)),adjacent(up,location(7,6)),adjacent(down,location(7,8)),adjacent(left,location(6,7))]).
locAdjacent(location(7,8),[adjacent(right,location(8,8)),adjacent(up,location(7,7)),adjacent(down,location(7,9)),adjacent(left,location(6,8))]).
locAdjacent(location(7,9),[adjacent(right,location(8,9)),adjacent(up,location(7,8)),adjacent(left,location(6,9))]).
locAdjacent(location(8,0),[adjacent(down,location(8,1)),adjacent(left,location(7,0)),adjacent(right,location(9,0))]).
locAdjacent(location(8,1),[adjacent(up,location(8,0)),adjacent(down,location(8,2)),adjacent(left,location(7,1)),adjacent(right,location(9,1))]).
locAdjacent(location(8,2),[adjacent(up,location(8,1)),adjacent(down,location(8,3)),adjacent(left,location(7,2)),adjacent(right,location(9,2))]).
locAdjacent(location(8,3),[adjacent(up,location(8,2)),adjacent(down,location(8,4)),adjacent(left,location(7,3)),adjacent(right,location(9,3))]).
locAdjacent(location(8,4),[adjacent(up,location(8,3)),adjacent(down,location(8,5)),adjacent(left,location(7,4)),adjacent(right,location(9,4))]).
locAdjacent(location(8,5),[adjacent(up,location(8,4)),adjacent(down,location(8,6)),adjacent(left,location(7,5)),adjacent(right,location(9,5))]).
locAdjacent(location(8,6),[adjacent(up,location(8,5)),adjacent(down,location(8,7)),adjacent(left,location(7,6)),adjacent(right,location(9,6))]).
locAdjacent(location(8,7),[adjacent(up,location(8,6)),adjacent(down,location(8,8)),adjacent(left,location(7,7)),adjacent(right,location(9,7))]).
locAdjacent(location(8,8),[adjacent(up,location(8,7)),adjacent(down,location(8,9)),adjacent(left,location(7,8)),adjacent(right,location(9,8))]).
locAdjacent(location(8,9),[adjacent(up,location(8,8)),adjacent(left,location(7,9)),adjacent(right,location(9,9))]).
locAdjacent(location(9,0),[adjacent(down,location(9,1)),adjacent(left,location(8,0))]).
locAdjacent(location(9,1),[adjacent(up,location(9,0)),adjacent(down,location(9,2)),adjacent(left,location(8,1))]).
locAdjacent(location(9,2),[adjacent(up,location(9,1)),adjacent(down,location(9,3)),adjacent(left,location(8,2))]).
locAdjacent(location(9,3),[adjacent(up,location(9,2)),adjacent(down,location(9,4)),adjacent(left,location(8,3))]).
locAdjacent(location(9,4),[adjacent(up,location(9,3)),adjacent(down,location(9,5)),adjacent(left,location(8,4))]).
locAdjacent(location(9,5),[adjacent(up,location(9,4)),adjacent(down,location(9,6)),adjacent(left,location(8,5))]).
locAdjacent(location(9,6),[adjacent(up,location(9,5)),adjacent(down,location(9,7)),adjacent(left,location(8,6))]).
locAdjacent(location(9,7),[adjacent(up,location(9,6)),adjacent(down,location(9,8)),adjacent(left,location(8,7))]).
locAdjacent(location(9,8),[adjacent(up,location(9,7)),adjacent(down,location(9,9)),adjacent(left,location(8,8))]).
locAdjacent(location(9,9),[adjacent(up,location(9,8)),adjacent(left,location(8,9))]).

// Location Direction Mappings
locDirToGoal(location(0,0),[down]).
locDirToGoal(location(0,1),[down]).
locDirToGoal(location(0,2),[none]).
locDirToGoal(location(0,3),[up]).
locDirToGoal(location(0,4),[up]).
locDirToGoal(location(0,5),[up]).
locDirToGoal(location(0,6),[up]).
locDirToGoal(location(0,7),[up]).
locDirToGoal(location(0,8),[up]).
locDirToGoal(location(0,9),[up]).
locDirToGoal(location(1,0),[left,down]).
locDirToGoal(location(1,1),[left]).
locDirToGoal(location(1,3),[left]).
locDirToGoal(location(1,4),[left,up]).
locDirToGoal(location(1,5),[left,up]).
locDirToGoal(location(1,6),[left,up]).
locDirToGoal(location(1,7),[left,up]).
locDirToGoal(location(1,8),[left,up]).
locDirToGoal(location(1,9),[left,up]).
locDirToGoal(location(2,0),[left,down]).
locDirToGoal(location(2,1),[left]).
locDirToGoal(location(2,3),[left]).
locDirToGoal(location(2,4),[left,up]).
locDirToGoal(location(2,5),[left,up]).
locDirToGoal(location(2,6),[left,up]).
locDirToGoal(location(2,7),[left,up]).
locDirToGoal(location(2,8),[left,up]).
locDirToGoal(location(2,9),[left,up]).
locDirToGoal(location(3,0),[left,down]).
locDirToGoal(location(3,1),[left]).
locDirToGoal(location(3,2),[up,down]).
locDirToGoal(location(3,3),[left]).
locDirToGoal(location(3,4),[left,up]).
locDirToGoal(location(3,5),[left,up]).
locDirToGoal(location(3,6),[left,up]).
locDirToGoal(location(3,7),[left,up]).
locDirToGoal(location(3,8),[left,up]).
locDirToGoal(location(3,9),[left,up]).
locDirToGoal(location(4,0),[left,down]).
locDirToGoal(location(4,1),[left]).
locDirToGoal(location(4,2),[left,up,down]).
locDirToGoal(location(4,3),[left]).
locDirToGoal(location(4,4),[left,up]).
locDirToGoal(location(4,5),[left,up]).
locDirToGoal(location(4,6),[left,up]).
locDirToGoal(location(4,7),[left,up]).
locDirToGoal(location(4,8),[left,up]).
locDirToGoal(location(4,9),[left,up]).
locDirToGoal(location(5,0),[left,down]).
locDirToGoal(location(5,1),[left]).
locDirToGoal(location(5,2),[left,up,down]).
locDirToGoal(location(5,3),[left]).
locDirToGoal(location(5,4),[left,up]).
locDirToGoal(location(5,5),[left,up]).
locDirToGoal(location(5,6),[left,up]).
locDirToGoal(location(5,7),[left,up]).
locDirToGoal(location(5,8),[left,up]).
locDirToGoal(location(5,9),[left,up]).
locDirToGoal(location(6,0),[left,down]).
locDirToGoal(location(6,1),[left]).
locDirToGoal(location(6,2),[left,up,down]).
locDirToGoal(location(6,3),[left]).
locDirToGoal(location(6,4),[left,up]).
locDirToGoal(location(6,5),[left,up]).
locDirToGoal(location(6,6),[left,up]).
locDirToGoal(location(6,7),[left,up]).
locDirToGoal(location(6,8),[left,up]).
locDirToGoal(location(6,9),[left,up]).
locDirToGoal(location(7,0),[left,down]).
locDirToGoal(location(7,1),[left]).
locDirToGoal(location(7,2),[left,up,down]).
locDirToGoal(location(7,3),[left]).
locDirToGoal(location(7,4),[left,up]).
locDirToGoal(location(7,5),[left,up]).
locDirToGoal(location(7,6),[left,up]).
locDirToGoal(location(7,7),[left,up]).
locDirToGoal(location(7,8),[left,up]).
locDirToGoal(location(7,9),[left,up]).
locDirToGoal(location(8,0),[left,down]).
locDirToGoal(location(8,1),[left]).
locDirToGoal(location(8,2),[left,up,down]).
locDirToGoal(location(8,3),[left]).
locDirToGoal(location(8,4),[left,up]).
locDirToGoal(location(8,5),[left,up]).
locDirToGoal(location(8,6),[left,up]).
locDirToGoal(location(8,7),[left,up]).
locDirToGoal(location(8,8),[left,up]).
locDirToGoal(location(8,9),[left,up]).
locDirToGoal(location(9,0),[left,down]).
locDirToGoal(location(9,1),[left]).
locDirToGoal(location(9,2),[left,up,down]).
locDirToGoal(location(9,3),[left]).
locDirToGoal(location(9,4),[left,up]).
locDirToGoal(location(9,5),[left,up]).
locDirToGoal(location(9,6),[left,up]).
locDirToGoal(location(9,7),[left,up]).
locDirToGoal(location(9,8),[left,up]).
locDirToGoal(location(9,9),[left,up]).